### ISSUE TITLE
Applying the program to different regions

### ISSUE THREAD

**Issue by felix-wolf** [carlosesilva/iphone-x-availability-node-cli#2]
Hey Carlos!

I am really impressed with your application. 
My Question is, how easy is it to apply it to a different region, lets say Australia?
Would you have to rewrite it from scratch as we don't choose carriers when buying online?

Thanks for your answer,

Felix Wolf

**Comment by carlosesilva** [comment]
Hello Felix,

Thanks!

You would have to update the url used in `fetch` and probably the part numbers in the `partNumbers.json` file.

You can probably take a look at this fork someone created for the dutch people:
https://github.com/Jorijn/iphone-x-availability-node-cli


Best Regards,
Carlos
