### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by miroesq** [carlosesilva/iphone-x-availability-node-cli#5]
I have High Sierra installed on my 2017 MacBook pro and followed your install instructions. Unfortunately, when I type "npm install" I get the error "-bash: npm: command not found"

I tried searching to see how I can install npm, but couldn't find anything that helped me.

**Comment by jboone0052** [comment]
I'm not super familiar with macs but I would think it would likely have something do with node not being installed properly or node not being in your path variable.

**Comment by carlosesilva** [comment]
Yeah just like @jboone0052 said, make sure you have node installed since npm gets installed automatically with node. https://nodejs.org/en/
